
services:
  pulsar:
    image: "apachepulsar/pulsar:4.0.2"
    command: bin/pulsar standalone
    environment:
      PULSAR_MEM: "-Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    volumes:
      - ./schema.avsc:/pulsar/schemas/schema.avsc


    ports:
      - "6650:6650"
      - "8080:8080"
    restart: unless-stopped
    networks:
      - pulsar_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  pulsar-manager:
    image: "apachepulsar/pulsar-manager:v0.4.0"
    ports:
      - "9527:9527"
      - "7750:7750"
    depends_on:
      - pulsar
    environment:
      SPRING_CONFIGURATION_FILE: /pulsar-manager/pulsar-manager/application.properties
    networks:
      - pulsar_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  pulsar_network:
    name: pulsar_network
    driver: bridge