apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: raw-producer-pipeline
spec:
  vertices:
    - name: in
      source:
        generator:
          rpu: 1
          duration: 10s
          msgSize: 10
    - name: out
      volumes: # Shared between containers that are part of the same pod, useful for sharing configurations
        - name: pulsar-config-volume
          configMap:
            name: byte-arr-producer-config
            items:
              - key: application.yml
                path: application.yml
      sink:
        udsink:
          container:
            image: apache-pulsar-java:v0.3.0 # TO DO: Replace with quay.io link
            args: [ "--spring.config.location=file:/conf/application.yml" ] # Use external configuration file 
            imagePullPolicy: Never
            env:
              - name: PULSAR_AUTH_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: pulsar-producer-auth-secret
                    key: pulsar-token
            volumeMounts:
              - name: pulsar-config-volume
                mountPath: /conf
  edges:
    - from: in
      to: out